### ISSUE TITLE
Add syntax coloring in quick search

### ISSUE THREAD

**Issue by jabby** [eclipse-platform/eclipse.platform.text#103]
I'm not sure this is the right project. 

What do you think about adding syntax coloring to quick search dialog ? When I select one result to see if it's the code I'm lookin for, it will help me to figure out.

First I though that tm4e can provide the syntax coloring then I realised this will create a circular dependencies between platform and tm4e. I found issue #87 about the same kind of problem.

**Comment by mickaelistria** [comment]
The same comment would generally apply to any place where we show an extract of some file (typically to the Search results view as well).
AS you mentioned, it's relatively tricky as syntax highlighted is delegating to external editors & plugins and we may not want to load them all.

**Comment by jukzi** [comment]
I'm closing this issues as it probably can't be implemented. I'm sure the feature itself would be welcome. @jabby Just reopen if you could contribute a feasible implementation, starting with giving a Screenshot for a discussion how it would look like.
