### ISSUE TITLE
[TEST] Intermittent test failures in FileBufferFunctions.test6 on Windows/ Linux 

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.text#11]
org.eclipse.core.filebuffers.tests.FileBufferFunctions.test6 failed in the IBuild I20220407-0240 on windows with the below error

```
expected:<content[]> but was:<content[appendix]>

org.junit.ComparisonFailure: expected:<content[]> but was:<content[appendix]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at org.eclipse.core.filebuffers.tests.FileBufferFunctions.test6(FileBufferFunctions.java:253)
```

This is a followup to [Bug 571317](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571317)

The link to the test results is [org.eclipse.core.filebuffers.tests_ep424I-unit-win32-java11_win32.win32.x86_64_11](https://download.eclipse.org/eclipse/downloads/drops4/I20220407-0240/testresults/html/org.eclipse.core.filebuffers.tests_ep424I-unit-win32-java11_win32.win32.x86_64_11.html)

**Comment by ktatavarthi** [comment]
This test failed on Linux with Java 18 in the build [I20220706-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220706-1800/testresults/html/org.eclipse.core.filebuffers.tests_ep425I-unit-cen64-gtk3-java18_linux.gtk.x86_64_18.html) with the below error

```
expected:<... in a linked folder.[]> but was:<... in a linked folder.[appendix]>

org.junit.ComparisonFailure: expected:<... in a linked folder.[]> but was:<... in a linked folder.[appendix]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at org.eclipse.core.filebuffers.tests.FileBufferFunctions.test6(FileBufferFunctions.java:253) 
```

**Comment by akurtakov** [comment]
I monitor Linux failures daily and haven't seen this one in quite some time. Also I20220827-1800 Win tests hasn't failed. I'm closing this one now.
