### ISSUE TITLE
Add filter to File Search to remove nested project duplicate files

### ISSUE THREAD

**Issue by jjohnstn** [eclipse-platform/eclipse.platform.text#143]
When nested projects are searched, multiple matches will occur for each project that is above the matched file.  The file should be opened in the context of the innermost project and this is already done, but some users might want to pare down the list of matches to exclude the duplicates that don't occur in the innermost project.  This is an enhancement request to add a filter to do this in the Search result view.

**Comment by iloveeclipse** [comment]
For the record: this was merged in 4.27 and caused regression via https://github.com/eclipse-platform/eclipse.platform.text/issues/187
