### ISSUE TITLE
Merge repo with https://github.com/eclipse-platform/eclipse.platform.text

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.text#167]
To simplify our Github repo structure we should merge this repo with one of our bigger once.

I sugest to target https://github.com/eclipse-platform/eclipse.platform

Ok for you? @mickaelistria @akurtakov @laeubi

**Comment by akurtakov** [comment]
Please either fix the failing test or disable it if not easily fixable so platform repo stay clean building.

**Comment by akurtakov** [comment]
https://github.com/eclipse-platform/eclipse.platform.text/pull/162 is the one to look at as it tries to unify platform.text build to be same as platform one.

**Comment by iloveeclipse** [comment]
I believe platform.text should be rather part of platform.ui, not platform.

**Comment by mickaelistria** [comment]
> I believe platform.text should be rather part of platform.ui, not platform.

+1, I now remember we discussed it some time ago; and if we're to keep eclipse.platform.ui for a few more months; then it's better to move eclipse.platform.text into it.

**Comment by vogella** [comment]
> #162 is the one to look at as it tries to unify platform.text build to be same as platform one.

Done by disabling the failing test. @laeubi might have a solution to enable it again with another PR

**Comment by laeubi** [comment]
@vogella I think we can proceed here before M1?

**Comment by laeubi** [comment]
@vogella do you want to initiate the merge here for 2023-09-M1?

**Comment by merks** [comment]
@laeubi 

Thanks so much for doing this!  🏅 

I've updated/fixed the setups accordingly;   I let the existing working sets for platform.ui "consume" the bundles and features merged in from platform.text.

**Comment by laeubi** [comment]
@merks many thanks to keeping the setup up-to-date :+1:
