### ISSUE TITLE
Should code-mining be in italic?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.text#194]
In big pieces of code with many codeminings (parameter names, markers message, some actions...) visible, it's hard to differentiate codeminings from actual code. I suggest we make them italic by default, similarly to theater stage instructions.

**Comment by szarnekow** [comment]
Could you please provide a screenshot to illustrate the problem?

**Comment by mickaelistria** [comment]
Here is an example of what things can look like in current state:
![Screenshot from 2023-05-11 20-26-44](https://github.com/eclipse-platform/eclipse.platform.text/assets/469058/9608d3c8-8d77-47b0-b015-3e43d3876aae)
and what I suggest it could look like (with italic and slightly smaller font)
![Screenshot from 2023-05-11 20-54-02](https://github.com/eclipse-platform/eclipse.platform.text/assets/469058/1b20b32e-5306-4b1b-af86-da58c0c11b12)

Note that the proper place that controls the font in this case is `AbstractCodeMining.draw(...)`

**Comment by mickaelistria** [comment]
Let's target it for 4.29.
