### ISSUE TITLE
org.eclipse.ui.tests.concurrency.TestBug269121.testBug is failing on Windows

### ISSUE THREAD

**Issue by Shee43** [eclipse-platform/eclipse.platform.text#215]
In the Build [I20230525-0350](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/), the below tests in org.eclipse.ui.tests.concurrency.TestBug269121.testBug failed
on [win32](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/testresults/html/org.eclipse.ui.tests_ep428I-unit-win32-java17_win32.win32.x86_64_17.html)

>```
>java.lang.AssertionError: Deadlock occurred
>at org.junit.Assert.fail(Assert.java:89)
>at org.junit.Assert.assertTrue(Assert.java:42)
>at org.eclipse.ui.tests.concurrency.TestBug269121.testBug(TestBug269121.java:106)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>at java.base/java.lang.reflect.Method.invoke(Method.java:568)
>```

**Comment by jukzi** [comment]
duplicates https://github.com/eclipse-platform/eclipse.platform.ui/issues/429
