### ISSUE TITLE
Hover on hit Breakpoint relayouts wrong on entering

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-platform/eclipse.platform.text#23]
When I hit a breakpoint, there are two markers in the annotation bar: the breakpoint and the current instruction pointer. When I hover over the breakpoint, I get a popup displaying some information. The `information` being displayed is

```
<html><body text="#000000" bgcolor="#ffffe1"><p>Multiple markers at this line<ul><li>Debug Current Instruction Pointer</li><li>Line breakpoint:Float [line: 458]</li></ul></body></html>
```

rendering as 
```
Multiple markers at this line
  * Debug Current ....
```
When you hover over the popup, the popup is being displaced with an window that has focus and can be resized. However, the first line is not displayed as before, instead it shows as 
```
Multiple markers at this 
line
...
```

This hides a good portion of the popup text.

The trouble seems to be this: if we take the size of the control, then reapply that as in DefaultInformationControl.setSizeConstraints(), the text is layouted differently.
My suspicion is that the `INNER_BORDER` is not taken into account when computing the necessary size for the original control. When there is only a single line in the popup, the replacement works without breaking the first line.

**Comment by merks** [comment]
In my experience, the calculations that determine the width/size of some HTML text to display in a hover is horribly inaccurate and at best can be considered a heuristic.    :-(

**Comment by tsmaeder** [comment]
Also in the `LineBreakingReader` class: 

```
	 * Reads the next line. The lengths of the line will not exceed the given maximum width.
	 *
	 * @return the next line
	 * @throws IOException if an I/O error occurs
	 */
	public String readLine() throws IOException {
		if (fLine == null) {
			String line= fReader.readLine();
			if (line == null)
				return null;

			int lineLen= fGC.textExtent(line).x;
			if (lineLen < fMaxWidth) {
				return line;
			}
```
if we're looking for "will not exceed the given maximum width", we should compare with `<=`, not `<':
```
if (lineLen < fMaxWidth) {
```

Fixing the comparison fixes the problem with the first line.

**Comment by tsmaeder** [comment]
Using a text layout is blocked by https://github.com/eclipse-platform/eclipse.platform.swt/issues/184
