### ISSUE TITLE
Cannot Request Reviewers on PRs

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-platform/eclipse.platform.text#27]
I've opened a PR, but I can't request anyone as a reviewer. Even if I'm not a committer on the project, I'd still like to request a review.

**Comment by merks** [comment]
I've never seen a PR like this where there is no link to any changes.  I.e., I see nothing to review.  How did you create this PR?  From a topic/issue branch in your fork?

**Comment by merks** [comment]
I guess it should be linked to this:

https://github.com/tsmaeder/eclipse.platform.text/tree/562709_fix_size_on_replace

**Comment by laeubi** [comment]
> Even if I'm not a committer on the project, I'd still like to request a review.

You need at least triage access right to the repository to do you as far as I know. You can still simply `@<person>` mention the one in the PR and ask for a review.

**Comment by vogella** [comment]
Would be nice if all Eclipse top-level committers (JDT; PDE, Platform) would have triage rights for their repos. @tsmaeder can you open a help ticket request this. I approve as PMC member.

**Comment by mickaelistria** [comment]
@vogella FWIW, @tsmaeder is not a committer on eclipse.platform repo ( https://projects.eclipse.org/projects/eclipse.platform/who ), so I don't think there enough reason to shamble the world. It's still possible to ping on comment.
Either we open the capacity to add a reviewer to everyone, or only to committers; everything in-between will bring more complexity IMO.

**Comment by vogella** [comment]
@mickaelistria I don't see the increased complexity by allowing JDT committers to assign reviewers in Platform and vice versa but I'm also OK with giving the rights to add reviewer to everyone. I don't assume that the world is just waiting to abuse this power and if this happens we still can change it back.

WDYT?

**Comment by mickaelistria** [comment]
> WDYT?

I like the idea of opening more "soft management" fields to a wider audience.

**Comment by vogella** [comment]
> > WDYT?
> 
> I like the idea of opening more "soft management" fields to a wider audience, eg everyone.

Me too. Anyone against this? 

If we have disagreement among committers,, I can bring this to the PMC but maybe this time no one dislikes a proposal to change the existing setup?

**Comment by laeubi** [comment]
@vogella I don't think you can allow everyone to do so but it should be possible to have a "eclipse-commiter" group giving the triage right on all eclipse orgs/projects:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository#inviting-a-team-or-person

**Comment by akurtakov** [comment]
Have we made anything here ?

**Comment by vogella** [comment]
> Have we made anything here ?

Not AFAIK
