### ISSUE TITLE
Filesearch: each file is read twice

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.text#29]
Search could be improved: The file content should be cached:
![image](https://user-images.githubusercontent.com/51790620/169497035-6c61f20a-5575-4825-8fa4-5cab21970b3e.png)

**Comment by iloveeclipse** [comment]
If you plan to add caching, please be careful to release caches fast, otherwise search may lead to OOM pretty fast. 
To test, just search for "a" in all files in a bigger workspace.

**Comment by laeubi** [comment]
If really **each** file is read twice, should then the answer not be caching, but *sharing* the data so it is only read once?
