### ISSUE TITLE
Nested projects: Search and Quick search matches appear twice

### ISSUE THREAD

**Issue by humphreygao** [eclipse-platform/eclipse.platform.text#31]
Open one multi-module maven project, press Ctrl+Shift+Alt+L to invoke Quick Search, and search something. Every matching item will appear two times.
Or press Ctrl + H to invoke Search, in File Search tab and search something. Every match appears twice.

![image](https://user-images.githubusercontent.com/52394598/170168193-2f7ad275-fdb7-473d-99ee-baf4670aa6d3.png)

**Comment by laeubi** [comment]
The "normal" search has also this problem, I think it would be good to have a filter as a first step, that filters all items that have the same path prefix but with a shorter path so in your example the first should be filtered out.

**Comment by akurtakov** [comment]
@mickaelistria Isn't this one fixed now?

**Comment by mickaelistria** [comment]
I don't think it's fixed.

**Comment by jabby** [comment]
I tried today. It's not fixed in the latest release.

**Comment by jjohnstn** [comment]
I have created a fix that works by massaging a found item's file to be the file in the innermost project.  The normal logic to remove duplicate matches kicks in as the files are equal.  The added benefit is that clicking on the one file will use the proper editor meant to be used as specified by the file's real project (no more errors about a Java file not being found on a build classpath).

**Comment by enexusde** [comment]
Confirmed working. It is disabled by default. You have to enable it.
![grafik](https://github.com/eclipse-platform/eclipse.platform.text/assets/6880636/900080ca-90e8-4a70-b8fb-c71651e97457)
