### ISSUE TITLE
Copy-Paste doesn't trigger Linked Editing `IExitPolicy.doExit(...)`

### ISSUE THREAD

**Issue by vrubezhny** [eclipse-platform/eclipse.platform.text#33]
When using a linked editing to simultaneously modify the linked editing session is to be stopped when typing characters that are not allowed in the context, for example when a Space character is typed while editing a method name.
To stop linked editing we can use the  `IExitPolicy` interface: 
```
org.eclipse.jface.text.link.LinkedModeUI.IExitPolicy.doExit(LinkedModeModel, VerifyEvent, int, int)
```
this interface allow us to process the characters typed in by a user. And adopters can implement their own schemas to exit a linked editing session,

However a document cab be modified not only by typing characters, for example, users may use Copy-Paste operation to change a text, including during the linked editing session is on. A Copy-Paste operation doesn't generate any `VerifyEvent` events and, as result, when the text is that is to be pasted contains any "not allowed" characters, all those characters will be "copied" into the linked edited text regions.

Steps to reproduce:
- Open or create a java file that has a method defined and/or some occurrences of use of that method.
- Select some text containing the characters not allowed to be treated as method name characters (for example, containing spaces, braces, comas etc).
- Start `Refactor-Rename` on the selected method 
- Paste the copied text.
- FAIL: The method name occurrences will be changed by adding the copied text to every method name occurrence within the text, The syntax will be broken as the result.

The current Linked Editing API doesn't prevent this issue, neither adopters can prevent it while using the existing API

**Comment by iloveeclipse** [comment]
This caused over 20 new fails in https://download.eclipse.org/eclipse/downloads/drops4/I20221006-1800 on all platforms. 

Please investigate. 

See for example https://download.eclipse.org/eclipse/downloads/drops4/I20221006-1800/testresults/html/org.eclipse.jdt.text.tests_ep426I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

**Comment by iloveeclipse** [comment]
One example :
```
java.lang.NullPointerException
at org.eclipse.jface.text.link.LinkedModeUI.connect(LinkedModeUI.java:1013)
at org.eclipse.jface.text.link.LinkedModeUI.enter(LinkedModeUI.java:755)
at org.eclipse.jdt.internal.ui.text.template.contentassist.TemplateProposal.apply(TemplateProposal.java:299)
at org.eclipse.jdt.text.tests.contentassist.PostFixCompletionTest.applyProposal(PostFixCompletionTest.java:932)
at org.eclipse.jdt.text.tests.contentassist.PostFixCompletionTest.testArrayAccessVar(PostFixCompletionTest.java:347
```

**Comment by iloveeclipse** [comment]
> Please investigate.

That was a simple case of ignorance of the documented API contracts, so I've pushed a patch.

Fix should be https://github.com/eclipse-platform/eclipse.platform.text/pull/99
