### ISSUE TITLE
No code mining updated when using Ctrl+End (was: CodeMiningTest are failing on Windows and Mac)

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.text#34]
This is a duplicate of [Bug 571317](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571317) - No code mining updated when using Ctrl+End (was: CodeMiningTest are failing on Windows and Mac).

I will close the bug in bugzilla and this bug will be tracked here.

The below JFace text tests in org.eclipse.jface.text.tests.codemining.CodeMiningTest  fail in the nightly build on windows

1) testCodeMiningDoesntAlterFocus
2) testCodeMiningCtrlEnd
3) testCodeMiningCtrlHome
4) testCodeMiningFirstLine

**Comment by ktatavarthi** [comment]
The below tests failed in the IBuild  [I20220601-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220601-1800/testResults.php) on [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220601-1800/testresults/html/org.eclipse.jface.text.tests_ep424I-unit-win32-java11_win32.win32.x86_64_11.html)
- testCodeMiningDoesntAlterFocus
- testCodeMiningCtrlEnd
- testCodeMiningCtrlHome
- testCodeMiningFirstLine

**Comment by ktatavarthi** [comment]
The below tests failed in the IBuild [I20220817-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/) on [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)
- testCodeMiningDoesntAlterFocus
- testCodeMiningCtrlEnd
- testCodeMiningCtrlHome
- testCodeMiningFirstLine

**Comment by ktatavarthi** [comment]
The below tests failed in the IBuild [I20220824-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/) on [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)
- testCodeMiningDoesntAlterFocus
- testCodeMiningCtrlEnd
- testCodeMiningCtrlHome
- testCodeMiningFirstLine

**Comment by ktatavarthi** [comment]
The below tests failed in the IBuild [I20220831-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220831-1800/) on [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220831-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)
- testCodeMiningDoesntAlterFocus
- testCodeMiningCtrlEnd
- testCodeMiningCtrlHome
- testCodeMiningFirstLine

**Comment by ktatavarthi** [comment]
The below tests failed in the IBuild [I20220928-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/) on [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.jface.text.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html)
- testCodeMiningDoesntAlterFocus
- testCodeMiningCtrlEnd
- testCodeMiningCtrlHome
- testCodeMiningFirstLine

**Comment by jukzi** [comment]
can reproduce CodeMiningProjectionViewerTest.testCodeMiningDoesntAlterFocus() fails locally

**Comment by jukzi** [comment]
@mickaelistria 
test was added with
"Bug 576716 - Code mining update that change scrolling cause completion
popup to close on any keystroke"

The creterion "fViewer.getTextWidget().getLineVerticalIndent(0) > 0" fails.
The only thing that would update LineVerticalIndent would be InlinedAnnotationDrawingStrategy.draw(LineHeaderAnnotation, GC, StyledText, int, int, Color) but only under many conditions. annotation.getHeight() always returns 0, so the conditions are not met - which is a bug. that bug was introduced with "Bug 571121 - Frequently "editor cheese" with code minings".
When i revert that change the test passes. The problem is that CodeMiningLineHeaderAnnotation.fResolvedMinings is not set before the draw but is only set during CodeMiningLineHeaderAnnotation.draw(GC, StyledText, int, int, Color, int, int) which is now some lines too late.

**Comment by mickaelistria** [comment]
@jukzi , thanks for the investigation. If you have some fix in a PR, I'll happily review. However this part of the code is a bit fragile and can easily lead to rendering issue (such as the one described in bug 5711121, so it may happen to be more difficult than it seems (or maybe not...). If the behavior is correct from a usage/UI POV, then we may tweak the test; however I don't get why the `CodeMiningLineHeaderAnnotation.draw` doesn't happen within the 3 seconds used by the condition check; does it happen later or never?
