### ISSUE TITLE
brackets highlighting should not contains code mining text 

### ISSUE THREAD

**Issue by humphreygao** [eclipse-platform/eclipse.platform.text#47]
![image](https://user-images.githubusercontent.com/52394598/174938526-1e3aee64-e1af-40be-a9d5-c51f2f8e1a89.png)
please see the picture above, the caret is placed at the closing bracket, and the matching bracket highlighting contains the method parameter name codemining text.

**Comment by arihunta** [comment]
Hi folks, I'm hopeful new Eclipse contributor, and started looking at this as a possible first issue to tackle (in the hopes that it would be easy 🙃). Did a bit of poking around at the code, will drop the relevant links here. I'm not 100% sure I'm making much sense, being unfamiliar with the codebase, and UI programming at this level in general...

Seems the key class is `org.eclipse.jface.text.source.MatchingCharacterPainter`, and the draw in that happens [here](https://github.com/eclipse-platform/eclipse.platform.text/blob/master/org.eclipse.jface.text/src/org/eclipse/jface/text/source/MatchingCharacterPainter.java#L254-L258).

That delegates to `org.eclipse.swt.custom.StyledText.getTextBounds(int, int)` and then eventually `org.eclipse.swt.graphics.TextLayout.getBoundsInPixels(int, int)` (I was in a `win32` source directory [here](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/Eclipse%20SWT/win32/org/eclipse/swt/graphics/TextLayout.java#L1688), guess I'd need to check other OSes as well...).

For the example I was looking at, `start` and `end` passed into that are the same. The length is based on a "run", whose length is determined [here](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/Eclipse%20SWT/win32/org/eclipse/swt/graphics/TextLayout.java#L3755-L3778) with some calls down to the OS. 

On the other side of things, the code mining annotation seems to be represented by `org.eclipse.jface.internal.text.codemining.CodeMiningLineContentAnnotation` [here](https://github.com/eclipse-platform/eclipse.platform.text/blob/master/org.eclipse.jface.text/src/org/eclipse/jface/internal/text/codemining/CodeMiningLineContentAnnotation.java).

I'm not quite sure how the two wire together yet. What seems tricky is that the run's widths seem to be calculated based just on the actual text in the line, not the annotation. So looking at the start of the one run to the start of the next, the annotation will always be included in the same run as the bracket.

It might be possible to limit the width of the matching character to a fixed amount, but I guess that'd break with certain cases, e.g. certain languages, or matching XML tags or something? I'm not sure if there's another way to be aware of the annotation when calculating rectangle width? Or if there would be consequences of having one run's width end before the annotation, and the next one's start after the annotation.

I'll do some more poking around, but thought to leave this comment here, so if someone is more knowledgeable they can confirm if I'm on the right track or point me in the right direction. Thanks!

**Comment by mickaelistria** [comment]
> It might be possible to limit the width of the matching character to a fixed amount, 

you can use `gc.textExtent` to compute the size of the text character (eg `(`) in the given context and then use this width to draw the box instead of the textBounds (which indeed include the annotation).

**Comment by arihunta** [comment]
Ahh, nice, that seems to work well, thanks! I'll get a pull request together.

**Comment by arihunta** [comment]
I've created a pull request for this here: https://github.com/eclipse-platform/eclipse.platform.text/pull/181
