### ISSUE TITLE
New bug...

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse-platform/eclipse.platform.text#93]
Log:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.php, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.google.gson,2.9.1
No repository found containing: osgi.bundle,org.apache.felix.gogo.runtime,1.1.6
No repository found containing: osgi.bundle,org.apache.felix.scr,2.2.2
No repository found containing: osgi.bundle,org.apache.xml.resolver,1.2.0.v20220715-1206
No repository found containing: osgi.bundle,org.bouncycastle.bcpg,1.71.0.v20220723-1943
No repository found containing: osgi.bundle,org.bouncycastle.bcprov,1.71.0.v20220723-1943
No repository found containing: osgi.bundle,org.eclipse.ant.core,3.6.500.v20220718-1722
No repository found containing: osgi.bundle,org.eclipse.cdt.core.win32.x86_64,6.0.700.202208222120
No repository found containing: osgi.bundle,org.eclipse.compare,3.8.500.v20220812-1406
No repository found containing: osgi.bundle,org.eclipse.compare.core,3.7.100.v20220812-1406
No repository found containing: osgi.bundle,org.eclipse.compare.win32,1.2.900.v20220812-1406
No repository found containing: osgi.bundle,org.eclipse.core.contenttype,3.8.200.v20220817-1539
No repository found containing: osgi.bundle,org.eclipse.core.databinding,1.11.100.v20220817-1444
No repository found containing: osgi.bundle,org.eclipse.core.expressions,3.8.200.v20220613-1047
No repository found containing: osgi.bundle,org.eclipse.core.externaltools,1.2.300.v20220618-1805
No repository found containing: osgi.bundle,org.eclipse.core.filesystem,1.9.500.v20220817-1539
No repository found containing: osgi.bundle,org.eclipse.core.filesystem.win32.x86_64,1.4.300.v20220812-1420
No repository found containing: osgi.bundle,org.eclipse.core.jobs,3.13.100.v20220817-1539
No repository found containing: osgi.bundle,org.eclipse.core.net,1.4.0.v20220813-1037
No repository found containing: osgi.bundle,org.eclipse.core.net.win32,1.0.100.v20220812-1406
No repository found containing: osgi.bundle,org.eclipse.core.net.win32.x86_64,1.1.700.v20220812-1406
No repository found containing: osgi.bundle,org.eclipse.core.resources,3.18.0.v20220828-0546
No repository found containing: osgi.bundle,org.eclipse.core.resources.win32.x86_64,3.5.500.v20220812-1420
No repository found containing: osgi.bundle,org.eclipse.core.runtime,3.26.0.v20220813-0916
No repository found containing: osgi.bundle,org.eclipse.debug.core,3.20.0.v20220811-0741
No repository found containing: osgi.bundle,org.eclipse.debug.ui,3.17.0.v20220817-1312
No repository found containing: osgi.bundle,org.eclipse.debug.ui.launchview,1.0.300.v20220811-0741
No repository found containing: osgi.bundle,org.eclipse.draw2d,3.11.100.202206170857
No repository found containing: osgi.bundle,org.eclipse.e4.core.commands,1.0.200.v20220629-1225
No repository found containing: osgi.bundle,org.eclipse.e4.core.contexts,1.11.0.v20220716-0839
No repository found containing: osgi.bundle,org.eclipse.e4.core.di,1.8.300.v20220817-1539
No repository found containing: osgi.bundle,org.eclipse.e4.core.di.annotations,1.7.200.v20220613-1008
No repository found containing: osgi.bundle,org.eclipse.e4.core.di.extensions,0.17.200.v20220613-1008
No repository found containing: osgi.bundle,org.eclipse.e4.core.di.extensions.supplier,0.16.400.v20220613-1047
No repository found containing: osgi.bundle,org.eclipse.e4.core.services,2.3.300.v20220613-1047
No repository found containing: osgi.bundle,org.eclipse.e4.ui.css.core,0.13.300.v20220809-1237
No repository found containing: osgi.bundle,org.eclipse.e4.ui.css.swt,0.14.600.v20220621-1327
No repository found containing: osgi.bundle,org.eclipse.e4.ui.dialogs,1.3.300.v20220815-1831
No repository found containing: osgi.bundle,org.eclipse.e4.ui.model.workbench,2.2.200.v20220817-1444
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench,1.13.200.v20220808-2019
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench.renderers.swt,0.15.600.v20220715-1400
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench.swt,0.16.600.v20220607-1204
No repository found containing: osgi.bundle,org.eclipse.emf.common,2.26.0.v20220817-1401
No repository found containing: osgi.bundle,org.eclipse.emf.ecore,2.28.0.v20220817-1401
No repository found containing: osgi.bundle,org.eclipse.emf.ecore.xmi,2.17.0.v20220817-1334
No repository found containing: osgi.bundle,org.eclipse.emf.edit.ui,2.22.0.v20220619-0533
No repository found containing: osgi.bundle,org.eclipse.epp.package.common,4.25.0.20220908-1200
No repository found containing: osgi.bundle,org.eclipse.epp.package.php,4.25.0.20220908-1200
No repository found containing: osgi.bundle,org.eclipse.equinox.app,1.6.200.v20220720-2012
No repository found containing: osgi.bundle,org.eclipse.equinox.bidi,1.4.200.v20220710-1223
No repository found containing: osgi.bundle,org.eclipse.equinox.common,3.16.200.v20220817-1601
No repository found containing: osgi.bundle,org.eclipse.equinox.frameworkadmin,2.2.100.v20220817-1208
No repository found containing: osgi.bundle,org.eclipse.equinox.http.registry,1.3.200.v20220720-2012
No repository found containing: osgi.bundle,org.eclipse.equinox.http.servlet,1.7.300.v20220726-1300
No repository found containing: osgi.bundle,org.eclipse.equinox.jsp.jasper,1.1.700.v20220801-1124
No repository found containing: osgi.bundle,org.eclipse.equinox.launcher.win32.win32.x86_64,1.2.600.v20220720-1916
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.core,2.9.200.v20220817-1208
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.director,2.5.400.v20220817-1208
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.director.app,1.2.200.v20220802-0626
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.engine,2.7.500.v20220817-1208
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.metadata,2.6.300.v20220817-1208
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.operations,2.6.100.v20220817-1208
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.publisher,1.7.200.v20220805-0804
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.repository,2.6.200.v20220819-1949
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.touchpoint.eclipse,2.3.300.v20220817-1208
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui,2.7.600.v20220817-1208
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui.sdk,1.2.100.v20220814-1551
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui.sdk.scheduler,1.5.400.v20220805-0804
No repository found containing: osgi.bundle,org.eclipse.equinox.preferences,3.10.100.v20220710-1223
No repository found containing: osgi.bundle,org.eclipse.equinox.registry,3.11.200.v20220817-1601
No repository found containing: osgi.bundle,org.eclipse.equinox.security,1.3.1000.v20220801-1135
No repository found containing: osgi.bundle,org.eclipse.equinox.security.ui,1.3.300.v20220710-1223
No repository found containing: osgi.bundle,org.eclipse.equinox.simpleconfigurator,1.4.100.v20220620-1617
No repository found containing: osgi.bundle,org.eclipse.gef,3.12.100.202206170857
No repository found containing: osgi.bundle,org.eclipse.help.base,4.3.800.v20220831-1800
No repository found containing: osgi.bundle,org.eclipse.help.ui,4.4.100.v20220619-1918
No repository found containing: osgi.bundle,org.eclipse.help.webapp,3.10.800.v20220714-2106
No repository found containing: osgi.bundle,org.eclipse.jetty.http,10.0.11
No repository found containing: osgi.bundle,org.eclipse.jetty.io,10.0.11
No repository found containing: osgi.bundle,org.eclipse.jetty.security,10.0.11
No repository found containing: osgi.bundle,org.eclipse.jetty.server,10.0.11
No repository found containing: osgi.bundle,org.eclipse.jetty.servlet,10.0.11
No repository found containing: osgi.bundle,org.eclipse.jetty.util,10.0.11
No repository found containing: osgi.bundle,org.eclipse.jetty.util.ajax,10.0.11
No repository found containing: osgi.bundle,org.eclipse.jface,3.27.0.v20220817-1444
No repository found containing: osgi.bundle,org.eclipse.jface.text,3.21.0.v20220817-1340
No repository found containing: osgi.bundle,org.eclipse.jsch.core,1.4.0.v20220813-1037
No repository found containing: osgi.bundle,org.eclipse.jsch.ui,1.4.200.v20220812-1406
No repository found containing: osgi.bundle,org.eclipse.lsp4e,0.14.0.202208241334
No repository found containing: osgi.bundle,org.eclipse.lsp4e.debug,0.14.0.202208051450
No repository found containing: osgi.bundle,org.eclipse.lsp4j,0.15.0.v20220805-0131
No repository found containing: osgi.bundle,org.eclipse.lsp4j.debug,0.15.0.v20220805-0131
No repository found containing: osgi.bundle,org.eclipse.lsp4j.jsonrpc,0.15.0.v20220805-0131
No repository found containing: osgi.bundle,org.eclipse.lsp4j.jsonrpc.debug,0.15.0.v20220805-0131
No repository found containing: osgi.bundle,org.eclipse.ltk.core.refactoring,3.13.0.v20220822-0502
No repository found containing: osgi.bundle,org.eclipse.ltk.ui.refactoring,3.12.200.v20220808-2221
No repository found containing: osgi.bundle,org.eclipse.osgi,3.18.100.v20220817-1601
No repository found containing: osgi.bundle,org.eclipse.osgi.compatibility.state,1.2.700.v20220722-0431
No repository found containing: osgi.bundle,org.eclipse.osgi.services,3.11.0.v20220618-0838
No repository found containing: osgi.bundle,org.eclipse.osgi.util,3.7.100.v20220615-1601
No repository found containing: osgi.bundle,org.eclipse.platform,4.25.0.v20220831-1800
No repository found containing: osgi.bundle,org.eclipse.platform.doc.user,4.25.0.v20220830-0901
No repository found containing: osgi.bundle,org.eclipse.rcp,4.25.0.v20220831-1800
No repository found containing: osgi.bundle,org.eclipse.search,3.14.200.v20220817-1340
No repository found containing: osgi.bundle,org.eclipse.swt,3.121.0.v20220829-1402
No repository found containing: osgi.bundle,org.eclipse.swt.win32.win32.x86_64,3.121.0.v20220829-1402
No repository found containing: osgi.bundle,org.eclipse.team.core,3.9.500.v20220817-1539
No repository found containing: osgi.bundle,org.eclipse.team.genericeditor.diff.extension,1.1.100.v20220812-1406
No repository found containing: osgi.bundle,org.eclipse.team.ui,3.9.400.v20220817-1539
No repository found containing: osgi.bundle,org.eclipse.text,3.12.200.v20220817-1340
No repository found containing: osgi.bundle,org.eclipse.tm4e.core,0.5.0.202206232130
No repository found containing: osgi.bundle,org.eclipse.tm4e.languageconfiguration,0.5.0.202206241118
No repository found containing: osgi.bundle,org.eclipse.tm4e.registry,0.6.0.202206241118
No repository found containing: osgi.bundle,org.eclipse.tm4e.ui,0.6.0.202206241118
No repository found containing: osgi.bundle,org.eclipse.ui,3.201.100.v20220826-1037
No repository found containing: osgi.bundle,org.eclipse.ui.browser,3.7.200.v20220826-1037
No repository found containing: osgi.bundle,org.eclipse.ui.cheatsheets,3.7.400.v20220715-1705
No repository found containing: osgi.bundle,org.eclipse.ui.console,3.11.300.v20220811-1921
No repository found containing: osgi.bundle,org.eclipse.ui.editors,3.14.400.v20220730-1844
No repository found containing: osgi.bundle,org.eclipse.ui.externaltools,3.5.200.v20220618-1805
No repository found containing: osgi.bundle,org.eclipse.ui.forms,3.11.400.v20220817-1444
No repository found containing: osgi.bundle,org.eclipse.ui.ide,3.19.100.v20220820-0412
No repository found containing: osgi.bundle,org.eclipse.ui.ide.application,1.4.500.v20220623-0641
No repository found containing: osgi.bundle,org.eclipse.ui.intro,3.6.600.v20220619-1918
No repository found containing: osgi.bundle,org.eclipse.ui.intro.quicklinks,1.1.200.v20220619-1918
No repository found containing: osgi.bundle,org.eclipse.ui.intro.universal,3.4.300.v20220619-1918
No repository found containing: osgi.bundle,org.eclipse.ui.navigator,3.10.300.v20220817-1444
No repository found containing: osgi.bundle,org.eclipse.ui.net,1.4.100.v20220812-1406
No repository found containing: osgi.bundle,org.eclipse.ui.themes,1.2.2000.v20220614-2134
No repository found containing: osgi.bundle,org.eclipse.ui.views,3.11.200.v20220817-1444
No repository found containing: osgi.bundle,org.eclipse.ui.views.log,1.3.300.v20220717-1456
No repository found containing: osgi.bundle,org.eclipse.ui.views.properties.tabbed,3.9.200.v20220717-1456
No repository found containing: osgi.bundle,org.eclipse.ui.workbench,3.126.0.v20220823-0718
No repository found containing: osgi.bundle,org.eclipse.ui.workbench.texteditor,3.16.600.v20220809-1658
No repository found containing: osgi.bundle,org.eclipse.update.configurator,3.4.900.v20220718-1722
No repository found containing: osgi.bundle,org.eclipse.wildwebdeveloper,0.6.0.202206151321
No repository found containing: osgi.bundle,org.eclipse.wildwebdeveloper.embedder.node,0.3.0.202206231201
No repository found containing: osgi.bundle,org.eclipse.wildwebdeveloper.xml,0.15.0.202207081036
No repository found containing: osgi.bundle,org.eclipse.wst.common.snippets,1.2.600.v202207121617
No repository found containing: osgi.bundle,org.eclipse.wst.common.ui,1.2.200.v202207121617
No repository found containing: osgi.bundle,org.eclipse.wst.dtd.core,1.2.300.v202207121749
No repository found containing: osgi.bundle,org.eclipse.wst.dtd.ui,1.1.400.v202207121749
No repository found containing: osgi.bundle,org.eclipse.wst.sse.core,1.2.800.v202207121749
No repository found containing: osgi.bundle,org.eclipse.wst.sse.ui,1.7.500.v202207121749
No repository found containing: osgi.bundle,org.eclipse.wst.xml.core,1.2.600.v202207121749
No repository found containing: osgi.bundle,org.eclipse.wst.xml.ui,1.2.700.v202208280234
No repository found containing: osgi.bundle,org.eclipse.wst.xsd.ui,1.3.500.v202207121749
No repository found containing: osgi.bundle,org.eclipse.xsd,2.18.0.v20220616-0915
No repository found containing: osgi.bundle,org.eclipse.xtext.xbase.lib,2.28.0.v20220829-0436
No repository found containing: osgi.bundle,com.ibm.icu,67.1.0
No repository found containing: osgi.bundle,com.sun.jna,5.8.0
No repository found containing: osgi.bundle,com.sun.jna.platform,5.8.0
No repository found containing: binary,epp.package.php.executable.win32.win32.x86_64,4.25.0.20220908-1200
No repository found containing: osgi.bundle,javax.servlet.jsp-api,2.3.3
No repository found containing: osgi.bundle,org.apache.felix.gogo.command,1.1.2
No repository found containing: osgi.bundle,org.apache.felix.gogo.shell,1.1.4
No repository found containing: org.eclipse.update.feature,org.eclipse.e4.rcp,4.25.0.v20220829-1402
No repository found containing: osgi.bundle,org.eclipse.e4.ui.progress,0.3.500.v20220717-1456
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.common,2.27.0.v20220817-1401
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.ecore,2.29.0.v20220817-1401
No repository found containing: org.eclipse.update.feature,org.eclipse.epp.package.common.feature,4.25.0.20220908-1200
No repository found containing: org.eclipse.update.feature,org.eclipse.epp.package.php.feature,4.25.0.20220908-1200
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.core.feature,1.6.1500.v20220819-1949
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.extras.feature,1.4.1700.v20220819-1949
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.rcp.feature,1.4.1700.v20220819-1949
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.user.ui,2.4.1700.v20220819-1949
No repository found containing: org.eclipse.update.feature,org.eclipse.help,2.3.1100.v20220831-1800
No repository found containing: org.eclipse.update.feature,org.eclipse.platform,4.25.0.v20220831-1800
No repository found containing: binary,org.eclipse.platform.ide.executable.win32.win32.x86_64,4.25.0.I20220831-1800
No repository found containing: binary,org.eclipse.platform_root,4.25.0.v20220831-1800
No repository found containing: org.eclipse.update.feature,org.eclipse.rcp,4.25.0.v20220831-1800
No repository found containing: binary,org.eclipse.rcp_root,4.25.0.v20220831-1800
No repository found containing: org.eclipse.update.feature,org.eclipse.tm.terminal.connector.local.feature,10.7.1.202208160035
No repository found containing: org.eclipse.update.feature,org.eclipse.tm.terminal.connector.ssh.feature,10.7.1.202208160035
No repository found containing: org.eclipse.update.feature,org.eclipse.tm.terminal.connector.telnet.feature,10.7.1.202208160035
No repository found containing: org.eclipse.update.feature,org.eclipse.tm.terminal.control.feature,10.7.1.202208160035
No repository found containing: org.eclipse.update.feature,org.eclipse.tm.terminal.feature,10.7.1.202208160035
No repository found containing: org.eclipse.update.feature,org.eclipse.tm.terminal.view.feature,10.7.1.202208160035
No repository found containing: org.eclipse.update.feature,org.eclipse.wildwebdeveloper.embedder.node.feature,0.3.0.202206231201
No repository found containing: org.eclipse.update.feature,org.eclipse.wildwebdeveloper.feature,0.11.0.202206231201
No repository found containing: org.eclipse.update.feature,org.eclipse.wildwebdeveloper.xml.feature,0.15.0.202207081036
No repository found containing: org.eclipse.update.feature,org.eclipse.wst.common_ui.feature,3.23.0.v202207121617
No repository found containing: org.eclipse.update.feature,org.eclipse.wst.xml_core.feature,3.27.0.v202207150226
No repository found containing: org.eclipse.update.feature,org.eclipse.wst.xml_ui.feature,3.27.0.v202208280234
No repository found containing: osgi.bundle,org.osgi.service.cm,1.6.1.202109301733
No repository found containing: osgi.bundle,org.osgi.service.component,1.5.0.202109301733
No repository found containing: osgi.bundle,org.osgi.service.device,1.1.1.202109301733
No repository found containing: osgi.bundle,org.osgi.service.event,1.4.1.202109301733
No repository found containing: osgi.bundle,org.osgi.service.metatype,1.4.1.202109301733
No repository found containing: osgi.bundle,org.osgi.service.provisioning,1.2.0.201505202024
No repository found containing: osgi.bundle,org.osgi.service.upnp,1.2.1.202109301733
No repository found containing: osgi.bundle,org.osgi.service.useradmin,1.1.1.202109301733
No repository found containing: osgi.bundle,org.osgi.service.wireadmin,1.0.2.202109301733
No repository found containing: osgi.bundle,org.tukaani.xz,1.9.0

![1](https://user-images.githubusercontent.com/42765391/191992172-fde22e37-60ae-4bf4-ad6d-97f807886b8f.jpg)

![2](https://user-images.githubusercontent.com/42765391/191992185-b86bb864-b03e-4510-ae7a-ff12d41183e4.jpg)

**Comment by jayjupdhig** [comment]
![3](https://user-images.githubusercontent.com/42765391/191992386-96bd2a14-4197-4f3d-8c3b-f434c075e4a1.jpg)

**Comment by merks** [comment]
If you restart the IDE and try again, does the problem recur?

**Comment by vogella** [comment]
> If you restart the IDE and try again, does the problem recur?

Closing as we did not get a reply
